#!/bin/bash
echo ####if script#######
echo
echo "Enter user Name"
read Name: USER
echo
echo "User Name:$Name"
echo
echo "Enter SEX"
read SEX: PERSON
echo "SEX:$SEX"
echo
if [ $SEX == Male ];
   then
   echo "Eligible for Hardwork"
else 
if [ $SEX == Female ];
   then
   echo "Eligible for work"
fi
echo
echo "Enter Age"
read AGE: YEARS
echo "AGE $Age"
if 
