#!/bin/python
teststring= 'Heloo World'
test= ['Hello','Devops','world']
print teststring[0]
print teststring[0:2]
print teststring[0:3]
print teststring[0:4]
print teststring[0:5]
print teststring[0:-4]
print teststring[0:-3]
print teststring[0:-2]
print teststring[0:-1]
print teststring[0:]
print test[0]
print test[0]
print test[0]
print test[1]
print test[2]
print test[0:2]
print test[0:]

